FORMAT: 1A
HOST: http://dsc.inf.furb.br/

# DCE 

API para realização do trabalho 1 de programação web II

## Login [/login]

### Fazer Login [POST]
+ Request (application/json)
    + Attributes (Login)

+ Response 200 (application/json)

        {
            "token" : "hash"   
        }
        
+ Response 401 (application/json)

        {
            "message" : "Email ou usuario invalido"   
        }
        
## Noticias [/noticias]

### Lista Noticias [GET]
+ Response 200 (application/json)

        [
            {
                "id": "1",
                "publish_date": "2014-01-01T23:28:56.782Z",
                "title": "Câmara Municipal de Blumenau homenageia professor Mauro Marcelo Mattos, do DSC.",
                "subtitle": "A Câmara de Vereadores homenageou seis professores que atuam em escolas da rede pública",
                "body_news": "Os detalhes das apresentações................"
            },
            {
                "id": "2",
                "publish_date": "2015-01-01T23:28:56.782Z",
                "title": "1ª Feira de Inovação e Empreendedorismo de Blumenau",
                "subtitle": "Feira de inovação chega em bluemnau.",
                "body_news": "Os detalhes das apresentações................"
            }
        ]

### Informacoes de uma noticia [GET /noticias/{id}]
+ Response 200 (application/json)

        {
           "id": "2",
           "publish_date": "2015-01-01T23:28:56.782Z",
           "title": "1ª Feira de Inovação e Empreendedorismo de Blumenau",
           "subtitle": "Feira de inovação chega em bluemnau."
           "body_news": "Os detalhes das apresentações................"
        }
     
+ Response 404 (application/json)

        {
            "message": "Noticia não encontrada"
        }
        
### Salvar nova noticia [POST /noticias]
+ Request (application/json)
    + Attributes (Noticia)
    
+ Response 200 (application/json)

        {
            "message": "Noticia salva com sucesso"
        }
        
### Editar uma noticia [PUT /noticias/{id}]

+ Request (application/json)
    + Attributes (Noticia)
    
+ Request (application/json)

        {
            "title": "new title"
        }

+ Request (application/json)

        {
            "subtitle": "new subtitle"
        }
    
+ Request (application/json)

        {
            "body_news": "new body_news"
        }

+ Response 200 (application/json)

        {
            "message": "Noticia salva com sucesso"
        }

+ Response 404 (application/json)

        {
            "message": "Noticia não encontrada"
        }

### Deletar uma noticia [DELETE /noticias/{id}]
+ Response 204 (application/json)
        
+ Response 404 (application/json)

        {
            "message": "Noticia não encontrada"
        }

## Professor [/professor]

### Listar Professores [GET]
+ Response 200 (application/json)

+ Response 404 (application/json)

        {
            "message": "Nenhum professor encontrado"
        }
        
### Informaçoes sobre um Professores [GET /professor/<id>]
+ Response 200 (application/json)
        
+ Response 404 (application/json)

        {
            "message": "Nenhum professor encontrado"
        }


### Adicionar professor [POST]
+ Request (application/json)
    + Attributes (Professor)
    
+ Response 201 (application/json)

+ Response 401 (application/json)

        {
            "message": "Usuario não autorizado"
        }
    
### Deletar professor [DELETE /professor/{id}]
+ Response 204 (application/json)

+ Response 404 (application/json)

        {
            "message": "Professor não encontrado"
        }
    
+ Response 401 (application/json)

        {
            "message": "Usuario não autorizado"
        }
        
### Alterar professor [PUT /professor/{id}]

+ Request (application/json)

        {
            "formacao": "nova formacao",
            "nome": "novo nome",
            "areaConcetracao": "nova areaConcetracao",
            "areaTematicaCurso": "nova areaTematicaCurso",
            "areaPesquisa": "nova areaPesquisa",
            "descricao": "nova descricao",
            "disciplinas": "nova disciplinas",
            "sala": "nova sala",
            "emailPrincipal": "nova emailPrincipal",
            "linkSite": "nova linkSite",
            "linkSkype": "nova linkSkype",
            "gTalk": "nova gTalk",
            "linkCurriculo": "nova linkCurriculo",
            "horario": "nova horario"

        }

+ Request (application/json)

        {
            "formacao": "nova formacao"
        }
        
+ Request (application/json)

        {
            "nome": "novo nome"
        }
        
+ Request (application/json)

        {
            "areaConcetracao": "nova areaConcetracao"
        }
+ Request (application/json)

        {
            "areaTematicaCurso": "nova areaTematicaCurso"
        }
+ Request (application/json)

        {
            "areaPesquisa": "nova areaPesquisa"
        }
        
+ Request (application/json)

        {
            "descricao": "nova descricao"
        }

+ Request (application/json)

        {
            "disciplinas": "nova disciplinas"
        }

+ Request (application/json)

        {
            "sala": "nova sala"
        }

+ Request (application/json)

        {
            "emailPrincipal": "nova emailPrincipal"
        }

+ Request (application/json)

        {
            "linkSite": "nova linkSite"
        }

+ Request (application/json)

        {
            "linkSkype": "nova linkSkype"
        }

+ Request (application/json)

        {
            "gTalk": "nova gTalk"
        }

+ Request (application/json)

        {
            "linkCurriculo": "nova linkCurriculo"
        }

+ Request (application/json)

        {
            "horario": "nova horario"
        }
        
+ Response 201 (application/json)

+ Response 404 (application/json)
    
        {
            "message": "Professor não encontrado"
        }
        
+ Response 401 (application/json)

        {
            "message": "Usuario não autorizado"
        }

## Curso [/curso]

### Lista Curso [GET]
+ Response 200 (application/json)

        [
            {
                "id" : "1",
                "nome" : "Ciência da Computação - Matutino",
                "horario" : "Matutino"
                
            },
            {
                "id" : "2",
                "nome" : "Ciência da Computação - Noturno",
                "horario" : "Noturno"
            },
            {
                "id" : "3",
                "nome" : "Sistemas de Informação - Noturno",
                "horario" : "Noturno"
            }
        ]
        
+ Response 404

        {
            "menssage" : "Cursos não encontrados!!"
        }
        
+ Response 408

        {
            "menssage" : "Tempo limite da operação excedido!!"
        }

### Lista Curso [GET/cursos/{id}]
+ Response 200 (application/json)

        [
            {
                "id" : "1",
                "nome" : "Ciência da Computação - Matutino",
                "horario" : "Matutino"
            }
        ]

+ Response 404

        {
            "menssage" : "Curso não encontrado!!"
        }
        
+ Response 408

        {
            "menssage" : "Tempo limite da operação excedido!!"
        }

### Criar curso [POST]

+ Request (application/json)
    + Attributes (Curso)

+ Response 201 (application/json)

+ Response 401 (application/json)


        {
            "menssage" : "Não foi possível criar um curso"
        }
        


### Deletar um curso [DELETE /curso/{id}]

+ Parameters
    + id (string)

+ Response 204 (application/json)
+ Response 401 (application/json)

### Alterar curso [PUT /curso/{id}]
+ Request (application/json)
    + Attributes (Curso)
        
+ Response 201 (application/json)
+ Response 401 (application/json)

## Monitores [/monitores]

### Alterar monitor [PUT /monitor/{id}]

+ Request (application/json)
        
        {
            "name": "Alex Seródio Gonçalves",
            "name": "Tecnologias em Computação Gráfica",
            "email": {
                "principal": "alexserodio@furb.br",
                "opcional": "alequis01@gmail.com"
            }
        }
        
+ Response 201 (application/json)

+ Response 401 (application/json)

        {
            "menssage" : "Monitor não encontrado!"
        }


## Grade [/grade]

### Alterar grade[PUT/grade/{id}]

+ Request (aplication/json)
    + Attributes (Grade)

+ Response 200 (application/json)
    
+ Response 200 (application/json)

        {
            "horario" : "1",
            "inicio" : "11:30",
            "fim" : "12:30",
            "periodo" : "Vespertino",
            "status" : "sucesso"
        }

+ Response 404 (application/json)

        {
            "menssage" : "Grade não encontrada!"
        }
    
+ Response 409 (application/json)

        {
            "menssage" : "Conflito de Grade!"
        }

+ Response 423 (application/json)

        {
            "menssage" : "Grade não pode ser alterada!"
        }


    
# Data Structures

## Curso(object)
+ id (number)
+ nome (string)
+ horario(object)

## Grade(object)
+ horario (number)
+ inicio (string)
+ fim (string)
+ periodo (string)

## Pessoa(object)
+ id (string)
+ nome (string)

## Professor(Pessoa)
+ formacao (string)
+ areaConcetracao (string)
+ areaTematicaCurso (string)
+ areaPesquisa (string)
+ descricao (string)
+ disciplinas (string)
+ sala (string)
+ emailPrincipal (string)
+ linkSite (string)
+ linkSkype (string)
+ gTalk (string)
+ linkCurriculo (string)
+ horario(object)

## Login (object)
+ email (string)
+ senha (string)

## Noticia
+ title (string)
+ subtitle (string)
+ body_news (string)